import PDFDocument from 'pdfkit';

export const generatePDF = (): PDFKit.PDFDocument => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: {
      top: 50,
      bottom: 50,
      left: 50,
      right: 50,
    }
  });

  doc
    .fontSize(25)
    .text('Hello pdf', 100, 100);

  doc
    .moveDown()
    .fontSize(14)
    .text('this is dynamice generated PDF generated by honojs', {
      width: 410,
      align: 'left',
    });

  doc.end();
  return doc;
};
